### ISSUE TITLE
Enable docker volume for local development

### ISSUE THREAD

**Issue by morenoh149** [mrclaytorres/pern-ts-vite-boilerplate#2]
What is the intended development workflow for the frontend?

When I make file changes the frontend does not automatically reload. Does this mean we need to enable a docker volume?

**Comment by mrclaytorres** [comment]
Hi @morenoh149 , I've added a delegated volume to the client service so it will have a watch mode. You can rebuild your docker image for the update and it should be good to go. Thanks.
